"""Add notations to posts/illusts

Revision ID: 00224e657d9a
Revises: b22bf01b773c
Create Date: 2021-06-09 13:00:14.082130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00224e657d9a'
down_revision = 'b22bf01b773c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_notations',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('notation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notation_id'], ['notation.id'], name=op.f('fk_post_notations_notation_id_notation')),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_post_notations_post_id_post')),
    sa.PrimaryKeyConstraint('post_id', 'notation_id', name=op.f('pk_post_notations'))
    )
    op.create_table('illust_notations',
    sa.Column('illust_id', sa.Integer(), nullable=False),
    sa.Column('notation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['illust_id'], ['illust.id'], name=op.f('fk_illust_notations_illust_id_illust')),
    sa.ForeignKeyConstraint(['notation_id'], ['notation.id'], name=op.f('fk_illust_notations_notation_id_notation')),
    sa.PrimaryKeyConstraint('illust_id', 'notation_id', name=op.f('pk_illust_notations'))
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illust_notations')
    op.drop_table('post_notations')
    # ### end Alembic commands ###


def upgrade_cache():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_cache():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_similarity():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_similarity():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

