"""Modify archive table

Revision ID: 00db0cdbc944
Revises: a903014faef2
Create Date: 2022-08-12 18:17:28.195820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00db0cdbc944'
down_revision = 'a903014faef2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


NAMING_CONVENTION = {
    "ix": 'ix_%(column_0_N_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('archive_data', schema=None, naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.drop_constraint('pk_archive_data', type_='primary')
        batch_op.alter_column('data_key', new_column_name='key')

    op.rename_table('archive_data', 'archive')

    with op.batch_alter_table('archive', schema=None, naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.create_primary_key('pk_archive', ['id'])
        batch_op.create_index(batch_op.f('ix_archive_type_archive_key'), ['type', 'key'], unique=True)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('archive_data', schema=None, naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_data_type_archive_data_data_key'))
        batch_op.drop_constraint('pk_archive', type_='primary')

    op.rename_table('archive', 'archive_data')

    with op.batch_alter_table('archive_data', schema=None, naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.create_primary_key('pk_archive_data', ['id'])
        batch_op.alter_column('key', new_column_name='data_key')

    # ### end Alembic commands ###

