"""Add type to posts

Revision ID: 45e6f79ff4c2
Revises: 93b5c7238893
Create Date: 2022-04-08 20:05:15.363368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e6f79ff4c2'
down_revision = '93b5c7238893'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


# Table definitions
t_post = sa.Table(
    'post',
    sa.MetaData(),
    sa.Column('id', sa.Integer),
    sa.Column('type', sa.String),
)


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(t_post.update().values(
        type='user_post',
        ))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###

