"""Add audio and duration to posts

Revision ID: 86a07c28c96a
Revises: 00db0cdbc944
Create Date: 2022-09-02 15:36:00.137742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a07c28c96a'
down_revision = '00db0cdbc944'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    print("Adding columns.")
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('audio')

    # ### end Alembic commands ###

