"""Add subscription pool element

Revision ID: be785ee97783
Revises: d77482ca6cda
Create Date: 2022-04-09 20:40:59.820041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be785ee97783'
down_revision = 'd77482ca6cda'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_pool_element',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pool_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('illust_url_id', sa.Integer(), nullable=False),
        sa.Column('keep', sa.String(length=16), nullable=True),
        sa.Column('md5', sa.String(length=32), nullable=True),
        sa.Column('expires', sa.DateTime(), nullable=True),
        sa.Column('deleted', sa.Boolean(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['illust_url_id'], ['illust_url.id'], name=op.f('fk_subscription_pool_element_illust_url_id_illust_url')),
        sa.ForeignKeyConstraint(['pool_id'], ['subscription_pool.id'], name=op.f('fk_subscription_pool_element_pool_id_subscription_pool')),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_subscription_pool_element_post_id_post')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_pool_element'))
    )
    op.create_table('subscription_pool_element_errors',
        sa.Column('subscription_pool_element_id', sa.Integer(), nullable=False),
        sa.Column('error_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['error_id'], ['error.id'], name=op.f('fk_subscription_pool_element_errors_error_id_error')),
        sa.ForeignKeyConstraint(['subscription_pool_element_id'], ['subscription_pool_element.id'], name=op.f('fk_subscription_pool_element_errors_subscription_pool_element_id_subscription_pool_element')),
        sa.PrimaryKeyConstraint('subscription_pool_element_id', 'error_id', name=op.f('pk_subscription_pool_element_errors'))
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_pool_element_errors')
    op.drop_table('subscription_pool_element')
    # ### end Alembic commands ###

