"""Add file parameters to uploads

Revision ID: de5fece98731
Revises: 5dde0c4906af
Create Date: 2021-05-24 19:41:19.994668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5fece98731'
down_revision = '5dde0c4906af'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('illust_url_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('media_filepath', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sample_filepath', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_upload_illust_url_id_illust_url'), 'illust_url', ['illust_url_id'], ['id'])

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_upload_illust_url_id_illust_url'), type_='foreignkey')
        batch_op.drop_column('sample_filepath')
        batch_op.drop_column('media_filepath')
        batch_op.drop_column('illust_url_id')

    # ### end Alembic commands ###


def upgrade_cache():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_cache():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_similarity():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_similarity():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

