"""Add post foreign keys to similarity tables

Revision ID: e0f58422fc61
Revises: 6a3814f17d95
Create Date: 2021-09-21 16:11:22.713276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f58422fc61'
down_revision = '6a3814f17d95'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similarity_data', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_similarity_data_post_id_post'), 'post', ['post_id'], ['id'])

    with op.batch_alter_table('similarity_pool', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_similarity_pool_post_id_post'), 'post', ['post_id'], ['id'])

    with op.batch_alter_table('similarity_pool_element', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_similarity_pool_element_post_id_post'), 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similarity_pool_element', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_similarity_pool_element_post_id_post'), type_='foreignkey')

    with op.batch_alter_table('similarity_pool', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_similarity_pool_post_id_post'), type_='foreignkey')

    with op.batch_alter_table('similarity_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_similarity_data_post_id_post'), type_='foreignkey')

    # ### end Alembic commands ###

