"""Add series boolean to pools

Revision ID: 213904f86fb4
Revises: 197e2575b90d
Create Date: 2021-09-06 13:37:30.219659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213904f86fb4'
down_revision = '197e2575b90d'
branch_labels = None
depends_on = None


# Table definitions
t_pool = sa.Table(
    'pool',
    sa.MetaData(),
    sa.Column('id', sa.Integer),
    sa.Column('series', sa.Boolean),
)


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series', sa.Boolean(), nullable=True))

    # Data migration
    print("Initializing table column")
    connection = op.get_bind()
    connection.execute(t_pool.update().values(
        series=False,
        ))

    # Set the column to non-null
    with op.batch_alter_table('pool', schema=None) as batch_op:
        batch_op.alter_column('series',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool', schema=None) as batch_op:
        batch_op.drop_column('series')

    # ### end Alembic commands ###


def upgrade_cache():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_cache():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_similarity():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_similarity():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

