"""Add multiple site accounts to artists

Revision ID: 8838f703858a
Revises: dc8fe9ef4e90
Create Date: 2021-04-30 15:50:33.175166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8838f703858a'
down_revision = 'dc8fe9ef4e90'
branch_labels = None
depends_on = None

# Table definitions
t_artist = sa.Table(
    'artist',
    sa.MetaData(),
    sa.Column('id', sa.Integer),
    sa.Column('site_account', sa.Unicode(length=255)),
)

t_label = sa.Table(
    'label',
    sa.MetaData(),
    sa.Column('id', sa.Integer()),
    sa.Column('name', sa.Unicode(length=255)),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    t_artist_site_accounts = op.create_table(
        'artist_site_accounts',
        sa.Column('label_id', sa.Integer(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
        sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
        sa.PrimaryKeyConstraint('label_id', 'artist_id'),
    )
    # ###

    connection = op.get_bind()
    # Select all existing names that need migrating.
    artist_results = connection.execute(sa.select([
        t_artist.c.id,
        t_artist.c.site_account,
        ])).fetchall()
    label_results = connection.execute(sa.select([
        t_label.c.id,
        t_label.c.name,
        ])).fetchall()
    seen_items = set(name for id_,name in label_results)
    # Insert description records (unique only)
    for id_, site_account in artist_results:
        if site_account in seen_items:
            continue
        connection.execute(t_label.insert().values(
            name=site_account,
            ))
        seen_items.add(site_account)
    label_results = connection.execute(sa.select([
        t_label.c.id,
        t_label.c.name,
        ])).fetchall()
    # Insert many-to-many records
    for artist_id, site_account in artist_results:
        for label_id, label_name in label_results:
            if site_account == label_name:
                connection.execute(t_artist_site_accounts.insert().values(
                    artist_id=artist_id,
                    label_id=label_id,
                    ))

    # ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('site_account')
    # ### end Alembic commands ###


def downgrade():
    # Table definitions
    t_artist_site_accounts = sa.Table(
        'artist_site_accounts',
        sa.MetaData(),
        sa.Column('label_id', sa.Integer()),
        sa.Column('artist_id', sa.Integer()),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_account', sa.VARCHAR(length=255), nullable=True))
    # ###

    connection = op.get_bind()
    label_results = connection.execute(sa.select([
        t_label.c.id,
        t_label.c.name,
        ])).fetchall()
    artist_site_account_results = connection.execute(sa.select([
        t_artist_site_accounts.c.artist_id,
        t_artist_site_accounts.c.label_id,
        ])).fetchall()
    # Update description column
    for artist_id, label_id in artist_site_account_results:
        site_account = next(filter(lambda x: x[0] == label_id, label_results), None)
        if site_account is None:
            continue
        connection.execute(t_artist.update().where(t_artist.c.id == artist_id).values(
            site_account=site_account[1],
            ))

    # ###
    op.drop_table('artist_site_accounts')
    # ### end Alembic commands ###
