"""Remove requery from artist and illust

Revision ID: ce08edf27b4d
Revises: fd22b755387e
Create Date: 2022-09-22 09:19:36.593188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce08edf27b4d'
down_revision = 'fd22b755387e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('requery')

    with op.batch_alter_table('illust', schema=None) as batch_op:
        batch_op.drop_column('requery')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illust', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requery', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requery', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###

