"""Update many columns to nonnullable

Revision ID: d28849cef17d
Revises: cf6510a015f0
Create Date: 2022-09-24 11:39:53.580896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28849cef17d'
down_revision = 'cf6510a015f0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('current_site_account',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('site_artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('illust', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('pages',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('illust_url', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('width',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pool', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('pool_element', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('similarity_data', schema=None) as batch_op:
        batch_op.alter_column('ratio',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('site_data', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('site_data', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('similarity_data', schema=None) as batch_op:
        batch_op.alter_column('ratio',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('pool_element', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('pool', schema=None) as batch_op:
        batch_op.alter_column('updated',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('illust_url', schema=None) as batch_op:
        batch_op.alter_column('width',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('illust', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pages',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('site_artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('current_site_account',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###

