"""Add alternate boolean to posts

Revision ID: d413db02c3e8
Revises: 97683f50f096
Create Date: 2022-07-02 18:06:15.329721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd413db02c3e8'
down_revision = '97683f50f096'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


# Table definitions
t_post = sa.Table(
    'post',
    sa.MetaData(),
    sa.Column('id', sa.Integer),
    sa.Column('alternate', sa.Boolean),
)


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternate', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(t_post.update().values(
        alternate=False,
        ))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('alternate',
               existing_type=sa.BOOLEAN(),
               nullable=False)


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('alternate')

    # ### end Alembic commands ###

