"""Subscription to subscription pool

Revision ID: d77482ca6cda
Revises: 45e6f79ff4c2
Create Date: 2022-04-09 20:15:36.333063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77482ca6cda'
down_revision = '45e6f79ff4c2'
branch_labels = None
depends_on = None


NAMING_CONVENTION = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None, naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.drop_constraint('fk_upload_subscription_id_subscription', type_='foreignkey')
        batch_op.drop_column('subscription_id')

    op.create_table('subscription_pool',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.Column('interval', sa.Float(), nullable=False),
        sa.Column('expiration', sa.Float(), nullable=True),
        sa.Column('status', sa.String(31), nullable=False),
        sa.Column('last_id', sa.Integer(), nullable=True),
        sa.Column('requery', sa.DateTime(), nullable=True),
        sa.Column('checked', sa.DateTime(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_pool')),
        sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name=op.f('fk_subscription_pool_artist_id_artist'))
    )

    op.create_table('subscription_pool_errors',
        sa.Column('subscription_pool_id', sa.Integer(), nullable=False),
        sa.Column('error_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['error_id'], ['error.id'], name=op.f('fk_subscription_pool_errors_error_id_error')),
        sa.ForeignKeyConstraint(['subscription_pool_id'], ['subscription_pool.id'], name=op.f('fk_subscription_pool_errors_subscription_pool_id_subscription_pool')),
        sa.PrimaryKeyConstraint('subscription_pool_id', 'error_id', name=op.f('pk_subscription_pool_errors'))
    )

    op.drop_table('subscription')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None, naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_upload_subscription_id_subscription', 'subscription', ['subscription_id'], ['id'])

    op.create_table('subscription',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('artist_id', sa.INTEGER(), nullable=False),
        sa.Column('requery', sa.DATETIME(), nullable=True),
        sa.Column('created', sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription'))
    )

    op.drop_table('subscription_pool_errors')
    op.drop_table('subscription_pool')
    # ### end Alembic commands ###
